### PR TITLE
fix for parsing response when setting indices

### PR DESCRIPTION
**Pull request by renewooller**
I noticed a problem parsing the response when running eg.

`CREATE INDEX ON :song(filename)`

This PR fixes that. 

Cheers

### CODE REVIEW

**Comment by Jonahss** [comment]
Thanks! merging and publishing.
Ooh thanks for including the version tag. awesome.

**Comment by Jonahss** [comment]
Published!

**Comment by renewooller** [comment]
Thanks for the merge. I noticed that 2.1.2, although in npm as latest, is not under releases in github. Is there some process that should have been followed to do that?

**Comment by Jonahss** [comment]
Oh huh, I think those releases look for the git tag for the version. But I thought I saw you had pushed the tag.
Usually, after running `npm version` you then have to push to github like `git push origin --follow-tags` and that will push the tags to the remote repo.

**Pull request merged**
