### PR TITLE
Fixes Boolean values getting as String

### PR DESCRIPTION
**Pull request by nishadcptn**

### CODE REVIEW

**Comment by Jonahss** [comment]
Hm hm. So the problem you ran into was that the client was returning a string like `"true"` instead of the boolean value `true`? If we're going to make this change, shouldn't we also parse ints and floats? What about `null`?

How does [ioredis](https://github.com/luin/ioredis) handle this? I'm sure they've had the same issue. We could solve it the same way they do.

**Comment by nishadcptn** [comment]
in the case of INT and FLOAT, they are Returning properly Without quotes. But in the case of BOOLEAN values its returning inside quotes, and in the case of `null` that is handled by the catch block itself.

**Comment by nishadcptn** [comment]
If `null` is used, it will work as before

**Comment by Jonahss** [comment]
Great! Thanks for explaining that.

**Comment by Jonahss** [comment]
Published as v3.0.0

**Comment by nishadcptn** [comment]
> Published as v3.0.0

Thanks for accepting the PR

**Comment by Jonahss** [comment]
Thanks for submitting!

**Pull request merged**
